#!/bin/bash
# build_sar_app.sh -- headless build of the SAR application as an HSS PAYLOAD for
# the PolarFire SoC Discovery Kit (MPFS095T), booting autonomously from microSD.
#
# Output: Default/sar_app.elf + Default/sar_app.bin (raw binary for the
# hss-payload-generator). Linked to run from the DDR exec address HSS jumps to
# (0x1000000000, see sar_app.ld + docs/HSS_INTEGRATION.md).
#
# Env mirrors mpfs/fpga/hss/build_hss.sh (SoftConsole v2022.2 riscv64-unknown-elf
# gcc 8.3.0). The mpfs-hal is built against the disco-kit MSS design config
# (src/boards/mpfs-discovery-kit/fpga_design_config, generated by the HSS build)
# and a payload mss_sw_config (config/, FIRST=LAST=hart1, loaded-by-bootloader).
set -e

SC="/c/Microchip/SoftConsole-v2022.2-RISC-V-747"
export SC_INSTALL_DIR="C:/Microchip/SoftConsole-v2022.2-RISC-V-747"
export PATH="$SC/build_tools/bin:$SC/riscv-unknown-elf-gcc/bin:$SC/python3:$PATH"

CC="riscv64-unknown-elf-gcc"
OBJCOPY="riscv64-unknown-elf-objcopy"
SIZE="riscv64-unknown-elf-size"

HERE="$(cd "$(dirname "$0")" && pwd)"
APP="$HERE/../libero_sar/softconsole/mpfs-hal-ddr-demo"
SRC="$APP/src"
PLAT="$SRC/platform"
HAL="$PLAT/mpfs_hal"
BOARD="$SRC/boards/mpfs-discovery-kit"
OUT="$HERE/Default"
mkdir -p "$OUT"

# --- disco-kit MSS design config (generated by the HSS build; gitignored as a
#     generated artifact, so sync it in from the canonical HSS build dir) ---
HSS_DC="${HSS_SRC:-/c/Users/lkwangsi/Documents/github/polarfire-soc/hart-software-services}/build/boards/mpfs-disco-kit/fpga_design_config"
DC_DST="$SRC/boards/mpfs-discovery-kit/fpga_design_config"
if [ ! -f "$DC_DST/fpga_design_config.h" ]; then
  echo "[sar_app] syncing disco-kit fpga_design_config from HSS build..."
  [ -f "$HSS_DC/fpga_design_config.h" ] || { echo "ERROR: $HSS_DC missing -- run mpfs/fpga/hss/build_hss.sh first"; exit 1; }
  mkdir -p "$DC_DST" && cp -r "$HSS_DC"/* "$DC_DST"/
fi

# --- target flags: match the SAR app .cproject (rv64g + double FP + compressed,
#     lp64d ABI, medany code model, strict align) ---
ARCH="-march=rv64gc -mabi=lp64d -mcmodel=medany -mstrict-align"
CFLAGS="$ARCH -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections \
  -Wall -Wno-unused-parameter -DSAR_SD_BOOT -DMPFS_DISCOVERY_KIT"
# Diagnostic build: SAR_DIAG_UART=1 streams live per-stage progress on the app UART (COM6)
# so a JTAG-less thin client can localize a focus-pipeline stall. Off by default.
if [ "${SAR_DIAG_UART:-0}" != "0" ]; then
  CFLAGS="$CFLAGS -DSAR_DIAG_UART"
  echo "[sar_app] SAR_DIAG_UART enabled -- diagnostic (UART-progress) build"
fi

INCS="\
  -I$HERE/config \
  -I$SRC \
  -I$PLAT \
  -I$HAL \
  -I$HAL/common \
  -I$PLAT/hal \
  -I$PLAT/drivers \
  -I$SRC/application \
  -I$BOARD"

# --- source list ---
SRCS="\
  $HAL/startup_gcc/mss_entry.S \
  $HAL/startup_gcc/mss_utils.S \
  $HAL/startup_gcc/system_startup.c \
  $HAL/startup_gcc/newlib_stubs.c \
  $PLAT/hal/hal_irq.c \
  $PLAT/hal/hw_reg_access.S \
  $PLAT/drivers/mss/mss_mmc/mss_mmc.c \
  $PLAT/drivers/mss/mss_mmc/mss_mmc_if.c \
  $PLAT/drivers/mss/mss_mmuart/mss_uart.c \
  $SRC/ddr_test/ddr_packet_test.c \
  $SRC/sar/sar_sequencer.c \
  $SRC/sar/sar_fft.c \
  $SRC/sar/sar_accel_driver.c \
  $SRC/sar/sar_resample_coeffs.c \
  $SRC/sar/sar_sd.c \
  $SRC/application/hart0/e51.c \
  $SRC/application/hart1/u54_1.c \
  $SRC/application/hart2/u54_2.c \
  $SRC/application/hart3/u54_3.c \
  $SRC/application/hart4/u54_4.c"
# whole mpfs_hal common + NWC tree (compiled even where HW-config-gated code is
# unreachable under IMAGE_LOADED_BY_BOOTLOADER=1, so every referenced symbol links)
SRCS="$SRCS $(ls $HAL/common/*.c) $(ls $HAL/common/nwc/*.c)"

echo "[sar_app] compiling..."
OBJS=""
for f in $SRCS; do
  o="$OUT/$(echo "$f" | sed 's#[/.]#_#g').o"
  $CC $CFLAGS $INCS -c "$f" -o "$o"
  OBJS="$OBJS $o"
done

echo "[sar_app] linking (exec addr 0x1000000000)..."
$CC $ARCH -O2 -nostartfiles -ffunction-sections -fdata-sections \
  --specs=nano.specs --specs=nosys.specs \
  -T "$HERE/sar_app.ld" -Wl,--gc-sections -Wl,-Map,"$OUT/sar_app.map" \
  $OBJS -lm -o "$OUT/sar_app.elf"

echo "[sar_app] emitting raw payload binary..."
$OBJCOPY -O binary "$OUT/sar_app.elf" "$OUT/sar_app.bin"

echo "[sar_app] build done:"
$SIZE "$OUT/sar_app.elf"
ls -la "$OUT/sar_app.elf" "$OUT/sar_app.bin"
